language: java

jdk: openjdk8

script: 
  - echo "Hola travis"
  - mvn package
  - ssh-keyscan -H 18.221.8.250 >> ~/.ssh/know_hosts
  - ssh-keyscan -H ec2-18-221-8-250.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  - scp -i acceso_instancia.pem target/*.war ubuntu@18.221.8.250:/tmp
  