language: java

jdk: openjdk8

script: 
  - echo "Hola travis"
  - mvn package
  - chmod 400 acceso_instancia.pem
  - ssh-keyscan -H 18.221.8.250 >> ~/.ssh/known_hosts
  - ssh-keyscan -H ec2-18-221-8-250.us-east-2.compute.amazonaws.com >> ~/.ssh/known_hosts
  #- ssh -i acceso_instancia.pem ubuntu@18.221.8.250 "rm -rf /var/lib/tomcat8/webapps/Netflix*"
  - scp -i acceso_instancia.pem target/*.war ubuntu@18.221.8.250:/var/lib/tomcat8/webapps/Netflix.war
