language: java

jdk: openjdk8

script: 
  - echo "Hola travis"
  - mvn package
  - chmod 400 acceso_instancia.pem
  - ssh-keyscan -H 18.221.8.250 >> ~/.ssh/know_hosts
  - scp -i acceso_instancia.pem target/*.war ubuntu@18.221.8.250:/tmp
  